/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import java.awt.ComponentOrientation;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mohit_Pc
 */
public class Accidsearch extends javax.swing.JFrame {

    /**
     * Creates new form Accidsearch
     */
    public Accidsearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtf_id = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textf_ex = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_names = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Enter cutomer id to search");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 78, 210, 30);
        jPanel1.add(txtf_id);
        txtf_id.setBounds(239, 90, 170, 20);

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search);
        btn_search.setBounds(60, 210, 100, 23);

        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit);
        btn_exit.setBounds(250, 210, 100, 23);

        textf_ex.setColumns(20);
        textf_ex.setRows(5);
        jScrollPane2.setViewportView(textf_ex);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 280, 420, 140);

        tbl_names.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tbl_names);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(500, 70, 360, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==btn_search)
        {
            Connection con=null;
            PreparedStatement ps=null;
            ResultSet rs=null;
            try
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                con=DriverManager.getConnection("jdbc:oracle:thin:@Mohit:1521:xe","scott","tiger");
                String dsplqry="Select * from customer where CUSTID=?";
                if(con!=null)
                    ps=con.prepareStatement(dsplqry);
                if(ps!=null)
                {
                    ps.setInt(1,Integer.parseInt(txtf_id.getText()));
                    rs=ps.executeQuery();
                    if(rs!=null)
                      tbl_names.setModel(DbUtils.resultSetToTableModel(rs));
                    else
                    {
                           textf_ex.append("---> SORRY!NAME NOT FOUND <---");
                           textf_ex.append("\n");
                    }
                }
            }catch(ClassNotFoundException cnf)
            {
                textf_ex.append(cnf.toString());
                textf_ex.append("\n");
            }catch(SQLException sq)
            {
             textf_ex.append(sq.toString());
              textf_ex.append("\n");
            }
        catch(Exception ex)
        {
              textf_ex.append(ex.toString());
              textf_ex.append("\n");
        }finally
         {
                try
                {
                    if(rs!=null)
                        rs.close();
                }catch(SQLException sq)
                {
                    textf_ex.append(sq.toString());
                     textf_ex.append("\n");
                }
                try
                {
                    if(ps!=null)
                        ps.close();
                }catch(SQLException sq)
                {
                     textf_ex.append(sq.toString());
                     textf_ex.append("\n");
                }
                try
                {
                    if(con!=null)
                        con.close();
                }catch(SQLException sq)
                {
                     textf_ex.append(sq.toString());
                     textf_ex.append("\n");
                }
            }
            //txtf_id.setText("");
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==btn_exit)
        {
            setVisible(false);
            new Search().setVisible(true);
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accidsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accidsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accidsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accidsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accidsearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_names;
    private javax.swing.JTextArea textf_ex;
    private javax.swing.JTextField txtf_id;
    // End of variables declaration//GEN-END:variables
}
