/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mohit_Pc
 */
public class NameSearch extends javax.swing.JFrame {

    /**
     * Creates new form NameSearch
     */
    public NameSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_custname = new javax.swing.JLabel();
        txtf_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_names = new javax.swing.JTable();
        btn_search = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textf_ex = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(null);

        lbl_custname.setText("   Enter Customer Name to search");
        jPanel1.add(lbl_custname);
        lbl_custname.setBounds(26, 67, 170, 30);
        jPanel1.add(txtf_name);
        txtf_name.setBounds(280, 70, 210, 30);

        tbl_names.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_names);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(542, 70, 320, 170);

        btn_search.setText("SEARCH");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search);
        btn_search.setBounds(170, 170, 100, 30);

        textf_ex.setColumns(20);
        textf_ex.setRows(5);
        jScrollPane2.setViewportView(textf_ex);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 240, 430, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==btn_search)
        {
            Connection con=null;
            PreparedStatement ps=null;
            ResultSet rs=null;
            try
          {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@Mohit:1521:xe","scott","tiger");
            String dsplqry="select * from customer where NAME=?";
            if(con!=null)
                ps=con.prepareStatement(dsplqry);
            if(ps!=null){
                ps.setString(1,txtf_name.getText());
                rs=ps.executeQuery();
                if(rs!=null)
                tbl_names.setModel(DbUtils.resultSetToTableModel(rs));
                else{
                    textf_ex.append("---> SORRY!NAME NOT FOUND <---");
                    textf_ex.append("\n");
                }
                           
            }
         }catch(ClassNotFoundException cnf)
         {
              textf_ex.append(cnf.toString());
              textf_ex.append("\n");
         }catch(SQLException sq)
        {
             textf_ex.append(sq.toString());
              textf_ex.append("\n");
        }
        catch(Exception ex)
        {
              textf_ex.append(ex.toString());
              textf_ex.append("\n");
        }finally
            {
                try
                {
                    if(rs!=null)
                        rs.close();
                }catch(SQLException sq)
                {
                    textf_ex.append(sq.toString());
                     textf_ex.append("\n");
                }
                try
                {
                    if(ps!=null)
                        ps.close();
                }catch(SQLException sq)
                {
                     textf_ex.append(sq.toString());
                     textf_ex.append("\n");
                }
                try
                {
                    if(con!=null)
                        con.close();
                }catch(SQLException sq)
                {
                     textf_ex.append(sq.toString());
                     textf_ex.append("\n");
                }
            }
            txtf_name.setText("");
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NameSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NameSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NameSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NameSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NameSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_custname;
    private javax.swing.JTable tbl_names;
    private javax.swing.JTextArea textf_ex;
    private javax.swing.JTextField txtf_name;
    // End of variables declaration//GEN-END:variables
}
